### ISSUE TITLE
question and suggestion 

### ISSUE THREAD

**Issue by littlekatter330** [VvSeanGTvV/V5-Reborn-Java#3]
when will the blocks be added to the tech tree and will you add vanguard (planed naval unit), and v5 scorch that creslex showed in his vid "mindustry v6 early preview (spoilers)"

**Comment by VvSeanGTvV** [comment]
Sorry if I didn't your question, but I added it in **1.2 Preview Build 2**, but idk where the v5 scorch in the video!
